cluster_color_panel <- function(target.var){
  
  col_pan <- data.frame(
    r = c(230,
          245,
          255,
          191,
          60,
          66,
          67,
          145,
          240,
          169,
          70),
    g = c(25,
          130,
          225,
          239,
          180,
          212,
          99,
          30,
          50,
          169,
          70),
    b = c(75,
          49,
          25,
          69,
          75,
          244,
          216,
          180,
          230,
          169,
          70),
    NEE = c(0, ## 0 as not used
            0,
            0,
            0,
            2,
            3,
            8,
            9,
            20,
            99, ## 99 as all others
            NA),
    LE = c(0,
           0,
           0,
           0,
           0,
           2,
           5,
           9,
           18,
           99,
           NA),
    H = c(0,
          0,
          0,
          1,
          2,
          5,
          6,
          7,
          9,
          99,
          NA),
    USTAR = c(0,
              0,
              0,
              0,
              0,
              1,
              2,
              3,
              9,
              99,
              NA),
    NETRAD = c(0,
               0,
               0,
               0,
               1,
               2,
               3,
               4,
               6,
               99,
               NA),
    TA = c(0,
           0,
           0,
           0,
           4,
           5,
           6,
           7,
           8,
           99,
           NA),
    VPD = c(1,
            5,
            12,
            13,
            14,
            15,
            17,
            18,
            22,
            99,
            NA),
    SWC = c(0,
            0,
            0,
            0,
            0,
            1,
            3,
            4,
            5,
            99,
            NA)
  )
  
  col_pan_out <- col_pan[, c(1:3, which(colnames(col_pan) == target.var))]
  
  if(length(which(col_pan_out[, 4] == 0)) > 0)
    col_pan_out <- col_pan_out[-which(col_pan_out[, 4] == 0), ]
  
  return(col_pan_out)
}