cluster_color_panel <- function(target.var){
  
  col_pan <- data.frame(
    r = c(230,
          245,
          255,
          191,
          60,
          66,
          67,
          145,
          169,
          70),
    g = c(25,
          130,
          225,
          239,
          180,
          212,
          99,
          30,
          169,
          70),
    b = c(75,
          49,
          25,
          69,
          75,
          244,
          216,
          180,
          169,
          70),
    NEE = c(0, ## 0 as not used
            0,
            0,
            4,
            6,
            8,
            12,
            14,
            99, ## 99 as all others
            NA),
    NETRAD = c(0,
               2,
               3,
               4,
               5,
               6,
               7,
               10,
               99,
               NA),
    TA = c(0,
           0,
           0,
           3,
           4,
           5,
           6,
           7,
           99,
           NA),
    SWC = c(0,
            1,
            4,
            5,
            6,
            8,
            9,
            11,
            99,
            NA),
    VPD = c(4,
            5,
            8,
            11,
            13,
            14,
            17,
            19,
            99,
            NA),
    H = c(1,
          2,
          3,
          4,
          8,
          9,
          12,
          13,
          99,
          NA),
    LE = c(0,
           0,
           0,
           0,
           0,
           3,
           4,
           6,
           99,
           NA),
    USTAR = c(0,
              0,
              1,
              2,
              3,
              4,
              6,
              9,
              99,
              NA)
  )
  
  col_pan_out <- col_pan[, c(1:3, which(colnames(col_pan) == target.var))]
  
  if(length(which(col_pan_out[, 4] == 0)) > 0)
    col_pan_out <- col_pan_out[-which(col_pan_out[, 4] == 0), ]
  
  return(col_pan_out)
}